version: '29.2.1'


services:
  db:
    image: postgres:15-alpine
    container_name: radim_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: search_engine
    ports:
      - "5432:5432"    
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  crawler:
    build:
      context: ./RadimTheWebCrawler
      dockerfile: Dockerfile
    container_name: radim_crawler
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=passwd
      - DB_NAME=search_engine
      - START_WEB=https://wikipedia.org/
    restart: on-failure
  search_engine:
    build:
      context: ./RadimTheSearchEngine
      dockerfile: Dockerfile
    container_name: radim_search_engine
    tty: true
    stdin_open: true
    depends_on:
      - db
      - crawler
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=passwd
      - DB_NAME=search_engine
    restart: on-failure
volumes:
  pgdata:
